version: 2

multi-ecosystem-groups:
  build:
    schedule:
      interval: "monthly"

updates:
  - package-ecosystem: "gradle"
    directory: "./" # Hack to allow multiple definitions of Gradle
    patterns:
      - "gradle-wrapper"
      - "com.bakdata.release"
      - "com.bakdata.sonar"
      - "com.bakdata.sonatype"
      - "com.bakdata.jib"
      - "com.bakdata.avro"
      - "com.bakdata.mockito"
      # freefair plugins follow Gradle's versioning
      - "io.freefair*"
    cooldown:
      default-days: 7
      exclude:
        - "com.bakdata*"
    multi-ecosystem-group: "build"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
      exclude:
        - "com.bakdata*"
    ignore: # Should match the patterns that are selected for "build" multi-ecosystem Gradle updates
      - dependency-name: "gradle-wrapper"
      - dependency-name: "com.bakdata.release"
      - dependency-name: "com.bakdata.sonar"
      - dependency-name: "com.bakdata.sonatype"
      - dependency-name: "com.bakdata.jib"
      - dependency-name: "com.bakdata.avro"
      - dependency-name: "com.bakdata.mockito"
      - dependency-name: "io.freefair*"
    groups:
      kafka-dependencies:
        patterns:
          - "com.bakdata.kafka*"
          - "com.bakdata.fluent-kafka-streams-tests*"
          - "io.confluent*"
          - "org.apache.kafka*"
      log-dependencies:
        patterns:
          - "org.slf4j*"
          - "org.apache.logging.log4j*"
      test-dependencies:
        patterns:
          - "org.junit*"
          - "org.assertj*"
          - "*junit*"
          - "org.mockito*"
          - "org.testcontainers*"
          - "org.awaitility*"
        exclude-patterns:
          - "com.bakdata.fluent-kafka-streams-tests*"
      plugins:
        patterns:
          - "com.bakdata.release"
          - "com.bakdata.sonar"
          - "com.bakdata.sonatype"
      protobuf:
        patterns:
          - "com.google.protobuf*"
      freefair-plugins:
        patterns:
          - "io.freefair*"

  - package-ecosystem: "github-actions"
    directory: "./" # Hack to allow multiple definitions of GitHub Actions
    patterns:
      - "bakdata/ci-templates*"
    cooldown:
      default-days: 7
      exclude:
        - "bakdata/ci-templates*"
    multi-ecosystem-group: "build"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
      exclude:
        - "bakdata/ci-templates*"
    ignore: # Should match the patterns that are selected for "build" multi-ecosystem GitHub Actions updates
      - dependency-name: "bakdata/ci-templates*"
    groups:
      ci-templates:
        patterns:
          - "bakdata/ci-templates*"
