name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "The scope of the release (major, minor or patch)."
        type: choice
        required: true
        default: patch
        options:
          - patch
          - minor
          - major

jobs:
  java-gradle-release:
    name: Java Gradle
    uses: bakdata/ci-templates/.github/workflows/java-gradle-release.yaml@1.40.5
    with:
      java-version: 17
      release-type: "${{ inputs.release-type }}"
    secrets:
      github-email: "${{ secrets.GH_EMAIL }}"
      github-username: "${{ secrets.GH_USERNAME }}"
      github-token: "${{ secrets.GH_TOKEN }}"
